/**
 * Admin — Library AI autopilot.
 *
 * One screen, three tabs (Articles · Books · Products). Each tab gives the
 * admin total control over how the AI cron behaves:
 *   - Toggle the kind on/off
 *   - Pick a frequency (off / monthly / weekly / bi-weekly / daily)
 *   - Tune perRun, autoPublish, expireAfterDays
 *   - Edit the topic / category catalog the AI rotates through
 *   - Edit the tone instruction the writer follows
 *   - "Generate now" with optional topic / age override
 *   - Live queue of recently AI-generated items with archive button
 *
 * The cron is opt-in: until an admin flips `enabled` on for a kind, no AI
 * content gets generated. That keeps the Library "stale-free by default":
 * an admin who never visits this screen continues to see the existing
 * curated static content, untouched.
 */

import { Ionicons } from '@expo/vector-icons';
import { Stack } from 'expo-router';
import { useEffect, useState } from 'react';
import {
  ActivityIndicator,
  Image,
  Linking,
  Pressable,
  StyleSheet,
  Switch,
  Text,
  TextInput,
  View,
} from 'react-native';

import { AdminPage, ConfirmDialog, FilterBar, StatusBadge, ToolbarButton } from '../../components/admin/ui';
import { Colors, FontSize, Radius, Shadow, Spacing } from '../../constants/theme';
import {
  AiItem,
  archiveLibraryItem,
  DEFAULT_LIBRARY_AI,
  FREQUENCIES,
  FREQUENCY_LABELS,
  GenArticleInput,
  GenBooksInput,
  GenProductsInput,
  generateArticleNow,
  generateBooksNow,
  generateProductsNow,
  KindSettings,
  LibraryAiSettings,
  listRecentRuns,
  subscribeLibraryAiSettings,
  subscribeRecentAiItems,
  updateLibraryAiSettings,
} from '../../services/libraryAi';
import { useAuthStore } from '../../store/useAuthStore';

type Kind = 'articles' | 'books' | 'products';
const KIND_META: Record<Kind, { label: string; emoji: string; collection: Kind; sub: string }> = {
  articles: { label: 'Articles', emoji: '📰', collection: 'articles', sub: 'Long-form parenting reads, generated by GPT-4o-mini, hero image by Imagen.' },
  books:    { label: 'Books',    emoji: '📚', collection: 'books',    sub: 'Real, in-print titles verified through Google Books and linked to Amazon Kindle India.' },
  products: { label: 'Products', emoji: '🛍️', collection: 'products', sub: 'Brand-name baby/mother SKUs sold on Amazon.in / Flipkart, with AI-rendered thumbnails.' },
};

export default function LibraryAiAdmin() {
  const auth = useAuthStore((s) => s.user);
  const [tab, setTab] = useState<Kind>('articles');
  const [settings, setSettings] = useState<LibraryAiSettings>(DEFAULT_LIBRARY_AI);
  const [items, setItems] = useState<AiItem[]>([]);
  const [savingKey, setSavingKey] = useState<string | null>(null);
  const [globalErr, setGlobalErr] = useState<string | null>(null);

  // Live settings subscription
  useEffect(() => {
    const unsub = subscribeLibraryAiSettings(setSettings);
    return () => unsub();
  }, []);

  // Live AI items for the active tab
  useEffect(() => {
    const unsub = subscribeRecentAiItems(tab, setItems, 30);
    return () => unsub();
  }, [tab]);

  const kind = tab;
  const k = settings[kind];

  async function persistKindPatch(patch: Partial<KindSettings>) {
    if (!auth) return;
    setSavingKey(kind);
    try {
      await updateLibraryAiSettings(
        { uid: auth.uid, email: auth.email },
        { [kind]: { ...k, ...patch } } as Partial<LibraryAiSettings>,
      );
    } catch (e: any) {
      setGlobalErr(e?.message ?? String(e));
    } finally {
      setSavingKey(null);
    }
  }

  async function persistGlobal(patch: Partial<LibraryAiSettings>) {
    if (!auth) return;
    try {
      await updateLibraryAiSettings({ uid: auth.uid, email: auth.email }, patch);
    } catch (e: any) {
      setGlobalErr(e?.message ?? String(e));
    }
  }

  return (
    <>
      <Stack.Screen options={{ title: 'Library AI' }} />
      <AdminPage
        title="Library AI"
        description="Auto-pilot for the Library tab. Articles, books and products generated, refreshed and expired without lifting a finger."
        crumbs={[{ label: 'Admin', href: '/admin' }, { label: 'Library AI' }]}
        headerActions={
          <View style={s.headerCtrls}>
            <View style={s.pausedRow}>
              <Text style={s.pausedLabel}>Paused</Text>
              <Switch
                value={settings.paused}
                onValueChange={(v) => persistGlobal({ paused: v })}
                trackColor={{ false: '#e5e7eb', true: Colors.warning }}
              />
            </View>
          </View>
        }
        toolbar={
          <FilterBar
            chips={(Object.keys(KIND_META) as Kind[]).map((k2) => ({
              key: k2,
              label: `${KIND_META[k2].emoji} ${KIND_META[k2].label}`,
              count: items.length && k2 === tab ? items.length : undefined,
            }))}
            active={tab}
            onChange={(k2) => setTab(k2 as Kind)}
          />
        }
        error={globalErr}
      >
        <HowItWorksBanner kind={kind} enabled={k.enabled} paused={settings.paused} />

        <KindCard
          kind={kind}
          settings={k}
          saving={savingKey === kind}
          onPatch={persistKindPatch}
        />

        <GenerateNowCard kind={kind} settings={k} onError={setGlobalErr} />

        <QueueCard kind={kind} items={items} onError={setGlobalErr} />

        {kind === 'articles' && <RunsCard />}
      </AdminPage>
    </>
  );
}

// ─── Kind settings card ─────────────────────────────────────────────────────

function KindCard({
  kind,
  settings: k,
  saving,
  onPatch,
}: {
  kind: Kind;
  settings: KindSettings;
  saving: boolean;
  onPatch: (patch: Partial<KindSettings>) => void;
}) {
  const [topicDraft, setTopicDraft] = useState(k.topics.join('\n'));
  const [toneDraft, setToneDraft] = useState(k.tone);

  // Reset local edit fields when settings change underneath us.
  useEffect(() => { setTopicDraft(k.topics.join('\n')); }, [k.topics]);
  useEffect(() => { setToneDraft(k.tone); }, [k.tone]);

  const meta = KIND_META[kind];
  const cadenceText = describeCadence(k);

  return (
    <View style={s.card}>
      <View style={s.cardHeader}>
        <View style={{ flex: 1 }}>
          <Text style={s.cardTitle}>{meta.emoji} {meta.label} autopilot</Text>
          <Text style={s.cardSub}>{meta.sub}</Text>
        </View>
        <View style={s.toggleWrap}>
          <Text style={[s.toggleLabel, k.enabled && { color: Colors.primary }]}>
            {k.enabled ? 'Enabled' : 'Off'}
          </Text>
          <Switch
            value={k.enabled}
            onValueChange={(v) => onPatch({ enabled: v })}
            trackColor={{ false: '#e5e7eb', true: Colors.primary }}
          />
        </View>
      </View>

      {k.enabled ? (
        <View style={s.cadenceBanner}>
          <Ionicons name="time-outline" size={14} color={Colors.primary} />
          <Text style={s.cadenceText}>{cadenceText}</Text>
        </View>
      ) : (
        <View style={[s.cadenceBanner, { backgroundColor: '#f3f4f6' }]}>
          <Ionicons name="pause-outline" size={14} color={Colors.textMuted} />
          <Text style={[s.cadenceText, { color: Colors.textMuted }]}>
            Cron is off. Manual "Generate now" still works.
          </Text>
        </View>
      )}

      <View style={s.fieldRow}>
        <View style={{ flex: 1 }}>
          <Text style={s.label}>Frequency</Text>
          <View style={s.freqChips}>
            {FREQUENCIES.map((f) => (
              <Pressable
                key={f}
                onPress={() => onPatch({ frequency: f })}
                style={[s.freqChip, k.frequency === f && s.freqChipActive]}
              >
                <Text style={[s.freqChipText, k.frequency === f && s.freqChipTextActive]}>
                  {FREQUENCY_LABELS[f]}
                </Text>
              </Pressable>
            ))}
          </View>
        </View>
      </View>

      <View style={s.fieldGrid}>
        <NumberField
          label="Items per run"
          value={k.perRun}
          min={1}
          max={10}
          onChange={(v) => onPatch({ perRun: v })}
        />
        <NumberField
          label="Auto-archive after (days)"
          hint="0 = never expire"
          value={k.expireAfterDays}
          min={0}
          max={365}
          onChange={(v) => onPatch({ expireAfterDays: v })}
        />
        <View style={s.boolField}>
          <Text style={s.label}>Auto-publish</Text>
          <View style={s.toggleWrap}>
            <Text style={s.toggleLabel}>{k.autoPublish ? 'Yes' : 'No'}</Text>
            <Switch
              value={k.autoPublish}
              onValueChange={(v) => onPatch({ autoPublish: v })}
              trackColor={{ false: '#e5e7eb', true: Colors.primary }}
            />
          </View>
          <Text style={s.hint}>
            {k.autoPublish
              ? 'New items go live instantly.'
              : 'New items wait as drafts until you publish them in /admin/content.'}
          </Text>
        </View>
      </View>

      <View style={{ marginTop: Spacing.md }}>
        <Text style={s.label}>{kind === 'products' ? 'Categories' : 'Topic catalog'} (one per line)</Text>
        <Text style={s.hint}>
          The AI rotates through these. Add Indian-context topics, festival hooks, age-specific angles.
        </Text>
        <TextInput
          value={topicDraft}
          onChangeText={setTopicDraft}
          multiline
          style={[s.input, { minHeight: 120 }]}
          placeholder={kind === 'products' ? 'Feeding\nSkincare\nSleep' : 'Sleep\nWeaning\nIndian Festivals & Babies'}
          placeholderTextColor={Colors.textMuted}
          autoCapitalize="sentences"
        />
        <View style={s.rowRight}>
          <ToolbarButton
            label="Save catalog"
            icon="save-outline"
            variant="secondary"
            disabled={saving || topicDraft === k.topics.join('\n')}
            onPress={() => onPatch({
              topics: topicDraft
                .split('\n')
                .map((t) => t.trim())
                .filter(Boolean)
                .slice(0, 50),
            })}
          />
        </View>
      </View>

      <View style={{ marginTop: Spacing.md }}>
        <Text style={s.label}>Tone & style instruction</Text>
        <Text style={s.hint}>The writer model is told this verbatim. Change voice, locale, do/don't.</Text>
        <TextInput
          value={toneDraft}
          onChangeText={setToneDraft}
          multiline
          style={[s.input, { minHeight: 80 }]}
          placeholderTextColor={Colors.textMuted}
        />
        <View style={s.rowRight}>
          <ToolbarButton
            label="Save tone"
            icon="save-outline"
            variant="secondary"
            disabled={saving || toneDraft === k.tone}
            onPress={() => onPatch({ tone: toneDraft.trim() })}
          />
        </View>
      </View>

      <View style={{ marginTop: Spacing.md }}>
        <Text style={s.label}>Age buckets</Text>
        <Text style={s.hint}>Cron rotates through these so every age band gets fresh content.</Text>
        <View style={s.bucketWrap}>
          {k.ageBuckets.map((b) => (
            <View key={b.key} style={s.bucketChip}>
              <Text style={s.bucketLabel}>{b.label}</Text>
              <Text style={s.bucketRange}>
                {b.ageMin < 0 ? 'pre-birth' : `${b.ageMin}-${b.ageMax}m`}
              </Text>
            </View>
          ))}
        </View>
      </View>
    </View>
  );
}

function describeCadence(k: KindSettings): string {
  if (!k.enabled || k.frequency === 'off') return 'Manual only — cron will not fire.';
  const freqLabel = FREQUENCY_LABELS[k.frequency];
  const expiresLabel = k.expireAfterDays === 0
    ? 'Items never auto-archive.'
    : `Auto-archives after ${k.expireAfterDays} days.`;
  const publishLabel = k.autoPublish
    ? 'auto-publishes on generate'
    : 'lands as draft for review';
  return `${freqLabel} · ${k.perRun}/run · ${publishLabel}. ${expiresLabel}`;
}

// ─── Generate-now card ──────────────────────────────────────────────────────

function GenerateNowCard({
  kind,
  settings: k,
  onError,
}: {
  kind: Kind;
  settings: KindSettings;
  onError: (msg: string | null) => void;
}) {
  const [open, setOpen] = useState(false);
  const [running, setRunning] = useState(false);
  const [topic, setTopic] = useState('');
  const [bucketKey, setBucketKey] = useState<string>('');
  const [count, setCount] = useState<string>(String(k.perRun));
  const [publishMode, setPublishMode] = useState<'auto' | 'published' | 'draft'>('auto');
  const [lastResult, setLastResult] = useState<string | null>(null);

  async function run() {
    setRunning(true);
    onError(null);
    try {
      const publishOverride = publishMode === 'auto' ? undefined : publishMode;
      if (kind === 'articles') {
        const input: GenArticleInput = {
          topic: topic.trim() || undefined,
          ageBucketKey: (bucketKey || undefined) as any,
          publish: publishOverride as any,
        };
        const r = await generateArticleNow(input);
        if (!r.ok) throw new Error(`${r.code}: ${r.message}`);
        setLastResult(`✓ Generated "${r.title}" (${r.status}).${r.flags.length ? ` ${r.flags.length} flag(s).` : ''}`);
      } else if (kind === 'books') {
        const input: GenBooksInput = {
          topic: topic.trim() || undefined,
          ageBucketKey: (bucketKey || undefined) as any,
          count: parseInt(count, 10) || k.perRun,
          publish: publishOverride as any,
        };
        const r = await generateBooksNow(input);
        if (!r.ok) throw new Error(`${r.code}: ${r.message}`);
        setLastResult(`✓ Inserted ${r.inserted.length} book(s). Skipped ${r.skipped.length}.`);
      } else {
        const input: GenProductsInput = {
          category: topic.trim() || undefined,
          ageBucketKey: (bucketKey || undefined) as any,
          count: parseInt(count, 10) || k.perRun,
          publish: publishOverride as any,
        };
        const r = await generateProductsNow(input);
        if (!r.ok) throw new Error(`${r.code}: ${r.message}`);
        setLastResult(`✓ Inserted ${r.inserted.length} product(s). Skipped ${r.skipped.length}.`);
      }
    } catch (e: any) {
      const msg = e?.message ?? String(e);
      setLastResult(`✗ ${msg}`);
      onError(msg);
    } finally {
      setRunning(false);
    }
  }

  return (
    <View style={s.card}>
      <View style={s.cardHeader}>
        <View style={{ flex: 1 }}>
          <Text style={s.cardTitle}>⚡ Generate now</Text>
          <Text style={s.cardSub}>
            Run the {kind} pipeline ad-hoc. Useful when a festival or trend just dropped.
          </Text>
        </View>
        <ToolbarButton
          label={open ? 'Hide options' : 'Override options'}
          icon={open ? 'chevron-up-outline' : 'chevron-down-outline'}
          variant="ghost"
          onPress={() => setOpen((v) => !v)}
        />
      </View>

      {open && (
        <View style={s.gridTwo}>
          <View style={{ flex: 1 }}>
            <Text style={s.label}>{kind === 'products' ? 'Category override' : 'Topic override'}</Text>
            <TextInput
              value={topic}
              onChangeText={setTopic}
              placeholder={`Leave blank → AI picks from ${k.topics.length} topics`}
              placeholderTextColor={Colors.textMuted}
              style={s.input}
            />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={s.label}>Age bucket</Text>
            <View style={s.bucketWrap}>
              <Pressable
                style={[s.bucketChip, !bucketKey && s.bucketChipActive]}
                onPress={() => setBucketKey('')}
              >
                <Text style={s.bucketLabel}>Auto</Text>
              </Pressable>
              {k.ageBuckets.map((b) => (
                <Pressable
                  key={b.key}
                  style={[s.bucketChip, bucketKey === b.key && s.bucketChipActive]}
                  onPress={() => setBucketKey(b.key)}
                >
                  <Text style={s.bucketLabel}>{b.label}</Text>
                </Pressable>
              ))}
            </View>
          </View>
          {kind !== 'articles' && (
            <View style={{ flex: 1 }}>
              <Text style={s.label}>Count</Text>
              <TextInput
                value={count}
                onChangeText={setCount}
                style={s.input}
                keyboardType="number-pad"
              />
            </View>
          )}
          <View style={{ flex: 1 }}>
            <Text style={s.label}>Publish mode</Text>
            <View style={s.bucketWrap}>
              {(['auto', 'published', 'draft'] as const).map((m) => (
                <Pressable
                  key={m}
                  onPress={() => setPublishMode(m)}
                  style={[s.bucketChip, publishMode === m && s.bucketChipActive]}
                >
                  <Text style={s.bucketLabel}>{m}</Text>
                </Pressable>
              ))}
            </View>
          </View>
        </View>
      )}

      <View style={s.runRow}>
        <ToolbarButton
          label={running ? 'Generating…' : `Generate ${kind === 'articles' ? 'one article' : `${count} ${kind === 'books' ? 'books' : 'products'}`}`}
          icon="sparkles-outline"
          variant="primary"
          disabled={running}
          onPress={run}
        />
        {lastResult && (
          <Text style={[s.runResult, lastResult.startsWith('✗') && s.runResultBad]}>
            {lastResult}
          </Text>
        )}
      </View>
    </View>
  );
}

// ─── Queue card ─────────────────────────────────────────────────────────────

function QueueCard({
  kind,
  items,
  onError,
}: {
  kind: Kind;
  items: AiItem[];
  onError: (msg: string | null) => void;
}) {
  const [archiving, setArchiving] = useState<string | null>(null);
  const [confirm, setConfirm] = useState<AiItem | null>(null);

  async function doArchive(item: AiItem) {
    setArchiving(item.id);
    onError(null);
    try {
      await archiveLibraryItem(item.kind, item.id);
    } catch (e: any) {
      onError(e?.message ?? String(e));
    } finally {
      setArchiving(null);
      setConfirm(null);
    }
  }

  return (
    <View style={s.card}>
      <View style={s.cardHeader}>
        <View style={{ flex: 1 }}>
          <Text style={s.cardTitle}>📋 Recent generations</Text>
          <Text style={s.cardSub}>The last 30 AI-generated {kind}. Tap to inspect or archive.</Text>
        </View>
      </View>

      {items.length === 0 ? (
        <View style={s.emptyWrap}>
          <Text style={s.emptyEmoji}>{KIND_META[kind].emoji}</Text>
          <Text style={s.emptyTitle}>Nothing yet</Text>
          <Text style={s.emptyBody}>
            Run "Generate now" or wait for the next cron tick to populate this queue.
          </Text>
        </View>
      ) : (
        <View style={{ gap: 8 }}>
          {items.map((it) => (
            <QueueRow
              key={it.id}
              item={it}
              archiving={archiving === it.id}
              onArchive={() => setConfirm(it)}
            />
          ))}
        </View>
      )}

      <ConfirmDialog
        visible={!!confirm}
        title="Archive item?"
        body={confirm ? `Hide "${confirm.title}" from the Library? It stays in Firestore for audit.` : ''}
        destructive
        confirmLabel="Archive"
        onCancel={() => setConfirm(null)}
        onConfirm={async () => { if (confirm) await doArchive(confirm); }}
      />
    </View>
  );
}

function QueueRow({ item, archiving, onArchive }: { item: AiItem; archiving: boolean; onArchive: () => void }) {
  const ts = item.createdAt?.toDate?.()?.toLocaleString?.() ?? 'just now';
  const exp = item.expiresAt?.toDate?.();
  const expLabel = exp ? `expires ${exp.toLocaleDateString()}` : 'no expiry';
  const ageLabel = item.ageMin < 0
    ? 'pregnancy'
    : item.ageMax >= 999
      ? 'all ages'
      : `${item.ageMin}-${item.ageMax}m`;

  return (
    <View style={s.row}>
      {item.imageUrl ? (
        <Image source={{ uri: item.imageUrl }} style={s.rowThumb} resizeMode="cover" />
      ) : (
        <View style={[s.rowThumb, { backgroundColor: Colors.bgLight, alignItems: 'center', justifyContent: 'center' }]}>
          <Text style={{ fontSize: 22 }}>{KIND_META[item.kind].emoji}</Text>
        </View>
      )}
      <View style={{ flex: 1 }}>
        <Text style={s.rowTitle} numberOfLines={1}>{item.title}</Text>
        <Text style={s.rowSub} numberOfLines={1}>
          {item.topic ? `${item.topic} · ` : ''}{ageLabel} · {ts} · {expLabel}
        </Text>
        {item.flags.length > 0 && (
          <Text style={s.rowFlag}>⚠ {item.flags.join(', ')}</Text>
        )}
      </View>
      <View style={s.rowActions}>
        <StatusBadge
          label={item.status === 'published' ? 'Live' : item.status === 'archived' ? 'Archived' : 'Draft'}
          color={item.status === 'published' ? Colors.success : item.status === 'archived' ? Colors.textMuted : Colors.warning}
        />
        {item.url ? (
          <Pressable hitSlop={8} onPress={() => Linking.openURL(item.url!).catch(() => {})}>
            <Ionicons name="open-outline" size={18} color={Colors.textLight} />
          </Pressable>
        ) : null}
        <Pressable hitSlop={8} onPress={onArchive} disabled={item.status === 'archived' || archiving}>
          {archiving ? (
            <ActivityIndicator size="small" color={Colors.error} />
          ) : (
            <Ionicons name="archive-outline" size={18} color={item.status === 'archived' ? Colors.textMuted : Colors.error} />
          )}
        </Pressable>
      </View>
    </View>
  );
}

// ─── Recent runs (cron history) — articles tab only ────────────────────────

function RunsCard() {
  const [rows, setRows] = useState<{ id: string; ts: string; summary: string }[]>([]);
  const [loading, setLoading] = useState(false);

  async function load() {
    setLoading(true);
    try {
      const r = await listRecentRuns(10);
      setRows(r.map((x) => ({
        id: x.id,
        ts: x.ts?.toDate?.()?.toLocaleString?.() ?? '',
        summary: summarise(x.kindSummary),
      })));
    } finally {
      setLoading(false);
    }
  }
  useEffect(() => { void load(); }, []);

  return (
    <View style={s.card}>
      <View style={s.cardHeader}>
        <View style={{ flex: 1 }}>
          <Text style={s.cardTitle}>🕒 Cron history</Text>
          <Text style={s.cardSub}>The last 10 daily-cron runs. Useful when something didn't generate.</Text>
        </View>
        <ToolbarButton label="Refresh" icon="refresh" variant="ghost" onPress={load} disabled={loading} />
      </View>
      {rows.length === 0 ? (
        <Text style={s.empty}>{loading ? 'Loading…' : 'No runs yet — wait for tomorrow 06:30 IST.'}</Text>
      ) : (
        rows.map((r) => (
          <View key={r.id} style={s.runRowItem}>
            <Text style={s.runRowTs}>{r.ts}</Text>
            <Text style={s.runRowSummary}>{r.summary}</Text>
          </View>
        ))
      )}
    </View>
  );
}

function summarise(d: any): string {
  if (d?.kind === 'expire') {
    const b = d?.summary ?? {};
    return `Expired: articles=${b.articles ?? 0} · books=${b.books ?? 0} · products=${b.products ?? 0}`;
  }
  const parts: string[] = [];
  for (const k of ['articles', 'books', 'products'] as const) {
    const v = d?.[k];
    if (!v || v === 'skipped') { parts.push(`${k}: —`); continue; }
    parts.push(`${k}: ${v.ok}/${v.attempted}${v.errors?.length ? ` (${v.errors.length} err)` : ''}`);
  }
  return parts.join(' · ');
}

// ─── How-it-works banner ────────────────────────────────────────────────────

function HowItWorksBanner({ kind, enabled, paused }: { kind: Kind; enabled: boolean; paused: boolean }) {
  const meta = KIND_META[kind];
  const stepsByKind: Record<Kind, string[]> = {
    articles: [
      '1. Toggle "Enabled" on the card below.',
      '2. Pick a frequency (bi-weekly is the default — Sunday + Wednesday at 06:30 IST).',
      '3. Edit the topic catalog if you want different angles.',
      '4. Click "Generate now" to test — the article will appear in Library within seconds.',
    ],
    books: [
      '1. Toggle "Enabled" on the card below.',
      '2. Pick a frequency (monthly recommended — books are timeless).',
      '3. Each run searches Google Books for real titles, then deep-links to Amazon.in / Kindle India.',
      '4. Click "Generate now" with a topic to add a fresh batch immediately.',
    ],
    products: [
      '1. Toggle "Enabled" on the card below.',
      '2. Pick a frequency (weekly is the default — pricing drifts faster).',
      '3. Edit the categories list. AI uses well-known Indian-market brand names only.',
      '4. Each row links to Amazon search by default; switch to Flipkart per-run if you prefer.',
    ],
  };
  return (
    <View style={[s.banner, paused && s.bannerPaused]}>
      <View style={s.bannerHead}>
        <Text style={s.bannerTitle}>
          {paused ? '⏸ Globally paused' : enabled ? `✅ ${meta.label} autopilot is ON` : `💤 ${meta.label} autopilot is OFF`}
        </Text>
        <Text style={s.bannerSub}>
          {paused
            ? 'Toggle "Paused" off in the header to resume all kinds.'
            : enabled
              ? `Cron will publish ${meta.label.toLowerCase()} on the schedule below. You can still run "Generate now" any time.`
              : `Switch this on to let AI keep ${meta.label.toLowerCase()} fresh without you babysitting.`}
        </Text>
      </View>
      <View style={s.bannerSteps}>
        {stepsByKind[kind].map((step, i) => (
          <Text key={i} style={s.bannerStep}>{step}</Text>
        ))}
      </View>
    </View>
  );
}

// ─── Tiny field components ──────────────────────────────────────────────────

function NumberField({ label, hint, value, min, max, onChange }: {
  label: string;
  hint?: string;
  value: number;
  min: number;
  max: number;
  onChange: (n: number) => void;
}) {
  const [draft, setDraft] = useState(String(value));
  useEffect(() => { setDraft(String(value)); }, [value]);
  return (
    <View style={s.numField}>
      <Text style={s.label}>{label}</Text>
      {hint && <Text style={s.hint}>{hint}</Text>}
      <View style={s.numRow}>
        <Pressable
          style={s.numStep}
          onPress={() => onChange(Math.max(min, value - 1))}
        >
          <Ionicons name="remove" size={16} color={Colors.textDark} />
        </Pressable>
        <TextInput
          value={draft}
          onChangeText={setDraft}
          onBlur={() => {
            const n = parseInt(draft, 10);
            if (Number.isFinite(n)) onChange(Math.max(min, Math.min(max, n)));
            else setDraft(String(value));
          }}
          style={s.numInput}
          keyboardType="number-pad"
        />
        <Pressable
          style={s.numStep}
          onPress={() => onChange(Math.min(max, value + 1))}
        >
          <Ionicons name="add" size={16} color={Colors.textDark} />
        </Pressable>
      </View>
    </View>
  );
}

// ─── Styles ─────────────────────────────────────────────────────────────────

const s = StyleSheet.create({
  card: {
    backgroundColor: Colors.cardBg,
    borderRadius: Radius.xl,
    padding: Spacing.lg,
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    ...Shadow.sm,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.md, marginBottom: Spacing.md },
  cardTitle: { fontSize: FontSize.md, fontWeight: '800', color: Colors.textDark },
  cardSub: { fontSize: FontSize.xs, color: Colors.textLight, marginTop: 2 },

  toggleWrap: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  toggleLabel: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textLight },

  cadenceBanner: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    backgroundColor: Colors.primaryAlpha05,
    paddingHorizontal: Spacing.md,
    paddingVertical: 8,
    borderRadius: Radius.md,
    marginBottom: Spacing.md,
  },
  cadenceText: { fontSize: FontSize.xs, color: Colors.primary, fontWeight: '600', flex: 1 },

  fieldRow: { flexDirection: 'row', gap: Spacing.md, marginBottom: Spacing.sm },
  fieldGrid: { flexDirection: 'row', gap: Spacing.md, flexWrap: 'wrap' },
  gridTwo: {
    flexDirection: 'row', gap: Spacing.md, flexWrap: 'wrap',
    marginVertical: Spacing.md,
  },

  label: {
    fontSize: 11, fontWeight: '700',
    color: Colors.textLight,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  hint: { fontSize: FontSize.xs, color: Colors.textMuted, marginBottom: 6 },

  input: {
    backgroundColor: Colors.bgLight,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: 10,
    fontSize: FontSize.sm,
    color: Colors.textDark,
    borderWidth: 1,
    borderColor: Colors.border,
  },

  freqChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  freqChip: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    backgroundColor: Colors.bgLight,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
  },
  freqChipActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  freqChipText: { fontSize: FontSize.xs, color: Colors.textDark, fontWeight: '600' },
  freqChipTextActive: { color: '#fff' },

  numField: { minWidth: 160, flex: 1 },
  numRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  numStep: {
    width: 32, height: 32,
    borderRadius: Radius.md,
    backgroundColor: Colors.bgLight,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: Colors.borderSoft,
  },
  numInput: {
    flex: 1, textAlign: 'center',
    backgroundColor: Colors.cardBg,
    borderRadius: Radius.md,
    paddingVertical: 8,
    borderWidth: 1, borderColor: Colors.border,
    fontSize: FontSize.sm, fontWeight: '700', color: Colors.textDark,
  },

  boolField: { minWidth: 200, flex: 1 },

  bucketWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 },
  bucketChip: {
    paddingHorizontal: Spacing.md, paddingVertical: 6,
    backgroundColor: Colors.bgLight,
    borderRadius: 999,
    borderWidth: 1, borderColor: Colors.borderSoft,
  },
  bucketChipActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  bucketLabel: { fontSize: FontSize.xs, fontWeight: '600', color: Colors.textDark },
  bucketRange: { fontSize: 10, color: Colors.textMuted, marginTop: 1 },

  rowRight: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 6 },
  runRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, marginTop: Spacing.md, flexWrap: 'wrap' },
  runResult: { fontSize: FontSize.xs, color: Colors.success, fontWeight: '600' },
  runResultBad: { color: Colors.error },

  row: {
    flexDirection: 'row',
    gap: Spacing.md,
    backgroundColor: Colors.bgLight,
    borderRadius: Radius.md,
    padding: Spacing.md,
    alignItems: 'center',
  },
  rowThumb: {
    width: 56, height: 56,
    borderRadius: Radius.md,
    overflow: 'hidden',
    borderWidth: 1, borderColor: Colors.borderSoft,
  },
  rowTitle: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.textDark },
  rowSub: { fontSize: FontSize.xs, color: Colors.textLight, marginTop: 2 },
  rowFlag: { fontSize: FontSize.xs, color: Colors.warning, marginTop: 2, fontWeight: '600' },
  rowActions: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },

  emptyWrap: { alignItems: 'center', paddingVertical: Spacing.xl, gap: 6 },
  emptyEmoji: { fontSize: 32 },
  emptyTitle: { fontSize: FontSize.md, fontWeight: '700', color: Colors.textDark },
  emptyBody: { fontSize: FontSize.xs, color: Colors.textMuted, textAlign: 'center', maxWidth: 320 },
  empty: { fontSize: FontSize.xs, color: Colors.textMuted, paddingVertical: Spacing.md },

  runRowItem: { paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: Colors.borderSoft },
  runRowTs: { fontSize: 10, color: Colors.textMuted, fontVariant: ['tabular-nums'] },
  runRowSummary: { fontSize: FontSize.xs, color: Colors.textDark, marginTop: 2 },

  headerCtrls: { flexDirection: 'row', gap: Spacing.md, alignItems: 'center' },
  pausedRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  pausedLabel: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textLight },

  banner: {
    backgroundColor: Colors.primaryAlpha05,
    borderRadius: Radius.xl,
    padding: Spacing.lg,
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.primaryAlpha12,
  },
  bannerPaused: { backgroundColor: '#fff7ed', borderColor: '#fdba74' },
  bannerHead: { marginBottom: Spacing.md },
  bannerTitle: { fontSize: FontSize.md, fontWeight: '800', color: Colors.textDark },
  bannerSub: { fontSize: FontSize.xs, color: Colors.textLight, marginTop: 4 },
  bannerSteps: { gap: 6 },
  bannerStep: { fontSize: FontSize.xs, color: Colors.textDark, lineHeight: 18 },
});
