/**
 * Admin — Library AI autopilot + Content Manager (unified).
 *
 * Three tabs: Articles · Books · Products.
 *
 * Each tab has:
 *   1. AI autopilot controls — enable/frequency/topics/tone/generate-now
 *   2. Content library — ALL items (AI + manual) with full CRUD:
 *        view body • edit fields • add manual • publish/unpublish •
 *        archive (soft) • delete (hard)
 *   3. Cron run history (Articles tab only)
 *
 * The old separate "/admin/content" page covers Schemes & Yoga only.
 */

import { Ionicons } from '@expo/vector-icons';
import { Stack } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import {
  ActivityIndicator,
  Image,
  Linking,
  Modal,
  Pressable,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  TextInput,
  View,
} from 'react-native';

import {
  AdminPage,
  ConfirmDialog,
  FilterBar,
  StatusBadge,
  Toolbar,
  ToolbarButton,
} from '../../components/admin/ui';
import { Colors, FontSize, Radius, Shadow, Spacing } from '../../constants/theme';
import { createContent, deleteContent, updateContent } from '../../services/firebase';
import {
  archiveLibraryItem,
  DEFAULT_LIBRARY_AI,
  FREQUENCIES,
  FREQUENCY_LABELS,
  GenArticleInput,
  GenBooksInput,
  GenProductsInput,
  generateArticleNow,
  generateBooksNow,
  generateProductsNow,
  KindSettings,
  LibraryAiSettings,
  LibraryContentItem,
  listRecentRuns,
  subscribeAllLibraryItems,
  subscribeLibraryAiSettings,
  updateLibraryAiSettings,
} from '../../services/libraryAi';
import { useAuthStore } from '../../store/useAuthStore';

// ─── Types ──────────────────────────────────────────────────────────────────

type Kind = 'articles' | 'books' | 'products';
type StatusFilter = 'all' | 'published' | 'draft' | 'archived';

const KIND_META: Record<Kind, { label: string; emoji: string; sub: string }> = {
  articles: {
    label: 'Articles',
    emoji: '📰',
    sub: 'Long-form parenting reads, generated by GPT-4o-mini, hero image by Imagen.',
  },
  books: {
    label: 'Books',
    emoji: '📚',
    sub: 'Real, in-print titles verified through Google Books — linked to Amazon Kindle India.',
  },
  products: {
    label: 'Products',
    emoji: '🛍️',
    sub: 'Brand-name baby/mother SKUs sold on Amazon.in / Flipkart, with AI-rendered thumbnails.',
  },
};

// ─── Schemas (field specs for the edit form) ────────────────────────────────

interface FieldSpec {
  key: string;
  label: string;
  multiline?: boolean;
  numeric?: boolean;
  hint?: string;
}

const SCHEMAS: Record<Kind, FieldSpec[]> = {
  articles: [
    { key: 'title',     label: 'Title *' },
    { key: 'preview',   label: 'Preview *', multiline: true },
    { key: 'body',      label: 'Full body',  multiline: true },
    { key: 'topic',     label: 'Topic', hint: 'Feeding, Sleep, Nutrition…' },
    { key: 'readTime',  label: 'Read time',  hint: 'e.g. "4 min read"' },
    { key: 'emoji',     label: 'Emoji icon' },
    { key: 'tag',       label: 'Tag', hint: 'e.g. Breastfeeding' },
    { key: 'url',       label: 'External URL' },
    { key: 'imageUrl',  label: 'Header image URL' },
    { key: 'ageMin',    label: 'Age min (months)', numeric: true },
    { key: 'ageMax',    label: 'Age max (months)', numeric: true },
  ],
  books: [
    { key: 'title',       label: 'Title *' },
    { key: 'author',      label: 'Author *' },
    { key: 'description', label: 'Description', multiline: true },
    { key: 'topic',       label: 'Topic', hint: 'e.g. Pregnancy, Sleep' },
    { key: 'rating',      label: 'Rating (1–5)',  numeric: true },
    { key: 'reviews',     label: 'Review count',  numeric: true },
    { key: 'url',         label: 'Buy URL' },
    { key: 'sampleUrl',   label: 'Sample / preview URL' },
    { key: 'imageUrl',    label: 'Cover image URL' },
    { key: 'ageMin',      label: 'Age min (months)', numeric: true, hint: '-9 = pregnancy' },
    { key: 'ageMax',      label: 'Age max (months)', numeric: true, hint: '999 = all ages' },
  ],
  products: [
    { key: 'name',          label: 'Product name *' },
    { key: 'category',      label: 'Category',  hint: 'Feeding, Sleep, Skincare…' },
    { key: 'emoji',         label: 'Emoji' },
    { key: 'price',         label: 'Price (₹)',  numeric: true },
    { key: 'originalPrice', label: 'Original price (₹)', numeric: true },
    { key: 'rating',        label: 'Rating (1–5)',  numeric: true },
    { key: 'reviews',       label: 'Review count',  numeric: true },
    { key: 'badge',         label: 'Badge', hint: 'e.g. Best Seller' },
    { key: 'description',   label: 'Description', multiline: true },
    { key: 'url',           label: 'Affiliate / buy URL' },
    { key: 'imageUrl',      label: 'Image URL' },
    { key: 'ageMin',        label: 'Age min (months)', numeric: true },
    { key: 'ageMax',        label: 'Age max (months)', numeric: true },
  ],
};

function blankItem(kind: Kind): Record<string, any> {
  const item: Record<string, any> = {};
  SCHEMAS[kind].forEach((f) => { item[f.key] = ''; });
  return item;
}

// ─── Main screen ─────────────────────────────────────────────────────────────

export default function LibraryAiAdmin() {
  const auth = useAuthStore((s) => s.user);
  const [tab, setTab] = useState<Kind>('articles');
  const [settings, setSettings] = useState<LibraryAiSettings>(DEFAULT_LIBRARY_AI);
  const [globalErr, setGlobalErr] = useState<string | null>(null);
  const [savingKey, setSavingKey] = useState<string | null>(null);

  useEffect(() => {
    const unsub = subscribeLibraryAiSettings(setSettings);
    return () => unsub();
  }, []);

  const k = settings[tab];

  async function persistKindPatch(patch: Partial<KindSettings>) {
    if (!auth) return;
    setSavingKey(tab);
    try {
      await updateLibraryAiSettings(
        { uid: auth.uid, email: auth.email },
        { [tab]: { ...k, ...patch } } as Partial<LibraryAiSettings>,
      );
    } catch (e: any) {
      setGlobalErr(e?.message ?? String(e));
    } finally {
      setSavingKey(null);
    }
  }

  async function persistGlobal(patch: Partial<LibraryAiSettings>) {
    if (!auth) return;
    try {
      await updateLibraryAiSettings({ uid: auth.uid, email: auth.email }, patch);
    } catch (e: any) {
      setGlobalErr(e?.message ?? String(e));
    }
  }

  return (
    <>
      <Stack.Screen options={{ title: 'Library' }} />
      <AdminPage
        title="Library"
        description="Autopilot + content manager for Articles, Books & Products. AI keeps sections fresh — you stay in control."
        crumbs={[{ label: 'Admin', href: '/admin' }, { label: 'Library' }]}
        headerActions={
          <View style={s.headerCtrls}>
            <View style={s.pausedRow}>
              <Text style={s.pausedLabel}>Paused</Text>
              <Switch
                value={settings.paused}
                onValueChange={(v) => persistGlobal({ paused: v })}
                trackColor={{ false: '#e5e7eb', true: Colors.warning }}
              />
            </View>
          </View>
        }
        toolbar={
          <FilterBar
            chips={(Object.keys(KIND_META) as Kind[]).map((k2) => ({
              key: k2,
              label: `${KIND_META[k2].emoji} ${KIND_META[k2].label}`,
            }))}
            active={tab}
            onChange={(k2) => setTab(k2 as Kind)}
          />
        }
        error={globalErr}
      >
        <HowItWorksBanner kind={tab} enabled={k.enabled} paused={settings.paused} />

        <KindCard
          kind={tab}
          settings={k}
          saving={savingKey === tab}
          onPatch={persistKindPatch}
        />

        <GenerateNowCard kind={tab} settings={k} onError={setGlobalErr} />

        <ContentLibraryCard kind={tab} onError={setGlobalErr} />

        {tab === 'articles' && <RunsCard />}
      </AdminPage>
    </>
  );
}

// ─── How-it-works banner ─────────────────────────────────────────────────────

function HowItWorksBanner({ kind, enabled, paused }: { kind: Kind; enabled: boolean; paused: boolean }) {
  const meta = KIND_META[kind];
  const stepsByKind: Record<Kind, string[]> = {
    articles: [
      '1. Toggle "Enabled" — AI generates articles on your chosen schedule.',
      '2. Pick bi-weekly (Sun + Wed) as a starting cadence; adjust any time.',
      '3. Edit the topic catalog to add Indian-context or festival angles.',
      '4. Hit "Generate now" to test — the article appears in the library below within seconds.',
    ],
    books: [
      '1. Toggle "Enabled" — AI curates real books monthly (or your chosen cadence).',
      '2. Each run searches Google Books for actual titles + deep-links Amazon.in.',
      '3. Hit "Generate now" with a topic to seed a batch immediately.',
      '4. Titles are de-duplicated automatically — no repeats.',
    ],
    products: [
      '1. Toggle "Enabled" — AI adds well-known brand-name products on schedule.',
      '2. Edit categories to focus on sections users care about most.',
      '3. Each product links to Amazon.in or Flipkart search for easy purchase.',
      '4. Products auto-archive after 60 days so pricing doesn\'t go stale.',
    ],
  };
  return (
    <View style={[s.banner, paused && s.bannerPaused]}>
      <View style={s.bannerHead}>
        <Text style={s.bannerTitle}>
          {paused
            ? '⏸ Globally paused'
            : enabled
              ? `✅ ${meta.label} autopilot is ON`
              : `💤 ${meta.label} autopilot is OFF`}
        </Text>
        <Text style={s.bannerSub}>
          {paused
            ? 'Toggle "Paused" off in the header to resume all kinds.'
            : enabled
              ? `Cron publishes ${meta.label.toLowerCase()} on the schedule below. "Generate now" works any time.`
              : `Enable autopilot to let AI keep ${meta.label.toLowerCase()} fresh without babysitting.`}
        </Text>
      </View>
      <View style={s.bannerSteps}>
        {stepsByKind[kind].map((step, i) => (
          <Text key={i} style={s.bannerStep}>{step}</Text>
        ))}
      </View>
    </View>
  );
}

// ─── Kind settings card ──────────────────────────────────────────────────────

function KindCard({ kind, settings: k, saving, onPatch }: {
  kind: Kind;
  settings: KindSettings;
  saving: boolean;
  onPatch: (patch: Partial<KindSettings>) => void;
}) {
  const [topicDraft, setTopicDraft] = useState(k.topics.join('\n'));
  const [toneDraft, setToneDraft] = useState(k.tone);

  useEffect(() => { setTopicDraft(k.topics.join('\n')); }, [k.topics]);
  useEffect(() => { setToneDraft(k.tone); }, [k.tone]);

  const meta = KIND_META[kind];
  const cadenceText = describeCadence(k);

  return (
    <View style={s.card}>
      <View style={s.cardHeader}>
        <View style={{ flex: 1 }}>
          <Text style={s.cardTitle}>{meta.emoji} {meta.label} autopilot</Text>
          <Text style={s.cardSub}>{meta.sub}</Text>
        </View>
        <View style={s.toggleWrap}>
          <Text style={[s.toggleLabel, k.enabled && { color: Colors.primary }]}>
            {k.enabled ? 'Enabled' : 'Off'}
          </Text>
          <Switch
            value={k.enabled}
            onValueChange={(v) => onPatch({ enabled: v })}
            trackColor={{ false: '#e5e7eb', true: Colors.primary }}
          />
        </View>
      </View>

      {k.enabled ? (
        <View style={s.cadenceBanner}>
          <Ionicons name="time-outline" size={14} color={Colors.primary} />
          <Text style={s.cadenceText}>{cadenceText}</Text>
        </View>
      ) : (
        <View style={[s.cadenceBanner, { backgroundColor: '#f3f4f6' }]}>
          <Ionicons name="pause-outline" size={14} color={Colors.textMuted} />
          <Text style={[s.cadenceText, { color: Colors.textMuted }]}>
            Cron is off — "Generate now" still works.
          </Text>
        </View>
      )}

      <View style={s.fieldRow}>
        <View style={{ flex: 1 }}>
          <Text style={s.label}>Frequency</Text>
          <View style={s.freqChips}>
            {FREQUENCIES.map((f) => (
              <Pressable
                key={f}
                onPress={() => onPatch({ frequency: f })}
                style={[s.freqChip, k.frequency === f && s.freqChipActive]}
              >
                <Text style={[s.freqChipText, k.frequency === f && s.freqChipTextActive]}>
                  {FREQUENCY_LABELS[f]}
                </Text>
              </Pressable>
            ))}
          </View>
        </View>
      </View>

      <View style={s.fieldGrid}>
        <NumberField
          label="Items per run"
          value={k.perRun}
          min={1}
          max={10}
          onChange={(v) => onPatch({ perRun: v })}
        />
        <NumberField
          label="Auto-archive after (days)"
          hint="0 = never"
          value={k.expireAfterDays}
          min={0}
          max={365}
          onChange={(v) => onPatch({ expireAfterDays: v })}
        />
        <View style={s.boolField}>
          <Text style={s.label}>Auto-publish</Text>
          <View style={s.toggleWrap}>
            <Text style={s.toggleLabel}>{k.autoPublish ? 'Yes' : 'No'}</Text>
            <Switch
              value={k.autoPublish}
              onValueChange={(v) => onPatch({ autoPublish: v })}
              trackColor={{ false: '#e5e7eb', true: Colors.primary }}
            />
          </View>
          <Text style={s.hint}>
            {k.autoPublish
              ? 'New items go live instantly.'
              : 'New items land as drafts for your review.'}
          </Text>
        </View>
      </View>

      <View style={{ marginTop: Spacing.md }}>
        <Text style={s.label}>{kind === 'products' ? 'Categories' : 'Topic catalog'} (one per line)</Text>
        <Text style={s.hint}>AI rotates through these. Add Indian-context topics, festival hooks, age-specific angles.</Text>
        <TextInput
          value={topicDraft}
          onChangeText={setTopicDraft}
          multiline
          style={[s.input, { minHeight: 120 }]}
          placeholder={kind === 'products' ? 'Feeding\nSkincare\nSleep' : 'Sleep\nWeaning\nIndian Festivals & Babies'}
          placeholderTextColor={Colors.textMuted}
          autoCapitalize="sentences"
        />
        <View style={s.rowRight}>
          <ToolbarButton
            label="Save catalog"
            icon="save-outline"
            variant="secondary"
            disabled={saving || topicDraft === k.topics.join('\n')}
            onPress={() => onPatch({
              topics: topicDraft.split('\n').map((t) => t.trim()).filter(Boolean).slice(0, 50),
            })}
          />
        </View>
      </View>

      <View style={{ marginTop: Spacing.md }}>
        <Text style={s.label}>Tone & style instruction</Text>
        <Text style={s.hint}>The writer model is told this verbatim. Change voice, locale, do/don't.</Text>
        <TextInput
          value={toneDraft}
          onChangeText={setToneDraft}
          multiline
          style={[s.input, { minHeight: 80 }]}
          placeholderTextColor={Colors.textMuted}
        />
        <View style={s.rowRight}>
          <ToolbarButton
            label="Save tone"
            icon="save-outline"
            variant="secondary"
            disabled={saving || toneDraft === k.tone}
            onPress={() => onPatch({ tone: toneDraft.trim() })}
          />
        </View>
      </View>

      <View style={{ marginTop: Spacing.md }}>
        <Text style={s.label}>Age buckets</Text>
        <Text style={s.hint}>Cron rotates through these so every age band gets fresh content.</Text>
        <View style={s.bucketWrap}>
          {k.ageBuckets.map((b) => (
            <View key={b.key} style={s.bucketChip}>
              <Text style={s.bucketLabel}>{b.label}</Text>
              <Text style={s.bucketRange}>{b.ageMin < 0 ? 'pre-birth' : `${b.ageMin}-${b.ageMax}m`}</Text>
            </View>
          ))}
        </View>
      </View>
    </View>
  );
}

function describeCadence(k: KindSettings): string {
  if (!k.enabled || k.frequency === 'off') return 'Manual only — cron will not fire.';
  const expLabel = k.expireAfterDays === 0
    ? 'Items never auto-archive.'
    : `Auto-archives after ${k.expireAfterDays} days.`;
  const pubLabel = k.autoPublish ? 'auto-publishes on generate' : 'lands as draft for review';
  return `${FREQUENCY_LABELS[k.frequency]} · ${k.perRun}/run · ${pubLabel}. ${expLabel}`;
}

// ─── Generate-now card ───────────────────────────────────────────────────────

function GenerateNowCard({ kind, settings: k, onError }: {
  kind: Kind;
  settings: KindSettings;
  onError: (msg: string | null) => void;
}) {
  const [open, setOpen] = useState(false);
  const [running, setRunning] = useState(false);
  const [topic, setTopic] = useState('');
  const [bucketKey, setBucketKey] = useState('');
  const [count, setCount] = useState(String(k.perRun));
  const [publishMode, setPublishMode] = useState<'auto' | 'published' | 'draft'>('auto');
  const [lastResult, setLastResult] = useState<string | null>(null);

  async function run() {
    setRunning(true);
    onError(null);
    setLastResult(null);
    try {
      const pub = publishMode === 'auto' ? undefined : publishMode;
      if (kind === 'articles') {
        const input: GenArticleInput = {
          topic: topic.trim() || undefined,
          ageBucketKey: (bucketKey || undefined) as any,
          publish: pub as any,
        };
        const r = await generateArticleNow(input);
        if (!r.ok) throw new Error(`${r.code}: ${r.message}`);
        setLastResult(`✓ Generated "${r.title}" (${r.status}).${r.flags.length ? ` ${r.flags.length} flag(s).` : ''} Check the library below.`);
      } else if (kind === 'books') {
        const input: GenBooksInput = {
          topic: topic.trim() || undefined,
          ageBucketKey: (bucketKey || undefined) as any,
          count: parseInt(count, 10) || k.perRun,
          publish: pub as any,
        };
        const r = await generateBooksNow(input);
        if (!r.ok) throw new Error(`${r.code}: ${r.message}`);
        setLastResult(`✓ Added ${r.inserted.length} book(s). Skipped ${r.skipped.length}. See library below.`);
      } else {
        const input: GenProductsInput = {
          category: topic.trim() || undefined,
          ageBucketKey: (bucketKey || undefined) as any,
          count: parseInt(count, 10) || k.perRun,
          publish: pub as any,
        };
        const r = await generateProductsNow(input);
        if (!r.ok) throw new Error(`${r.code}: ${r.message}`);
        setLastResult(`✓ Added ${r.inserted.length} product(s). Skipped ${r.skipped.length}. See library below.`);
      }
    } catch (e: any) {
      const msg = e?.message ?? String(e);
      setLastResult(`✗ ${msg}`);
      onError(msg);
    } finally {
      setRunning(false);
    }
  }

  return (
    <View style={s.card}>
      <View style={s.cardHeader}>
        <View style={{ flex: 1 }}>
          <Text style={s.cardTitle}>⚡ Generate now</Text>
          <Text style={s.cardSub}>Run the {kind} pipeline ad-hoc. New items appear in the library below.</Text>
        </View>
        <ToolbarButton
          label={open ? 'Hide options' : 'Options'}
          icon={open ? 'chevron-up-outline' : 'options-outline'}
          variant="ghost"
          onPress={() => setOpen((v) => !v)}
        />
      </View>

      {open && (
        <View style={s.gridTwo}>
          <View style={{ flex: 1 }}>
            <Text style={s.label}>{kind === 'products' ? 'Category override' : 'Topic override'}</Text>
            <TextInput
              value={topic}
              onChangeText={setTopic}
              placeholder={`Blank → AI picks from ${k.topics.length} topics`}
              placeholderTextColor={Colors.textMuted}
              style={s.input}
            />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={s.label}>Age bucket</Text>
            <View style={s.bucketWrap}>
              <Pressable
                style={[s.bucketChip, !bucketKey && s.bucketChipActive]}
                onPress={() => setBucketKey('')}
              >
                <Text style={[s.bucketLabel, !bucketKey && { color: '#fff' }]}>Auto</Text>
              </Pressable>
              {k.ageBuckets.map((b) => (
                <Pressable
                  key={b.key}
                  style={[s.bucketChip, bucketKey === b.key && s.bucketChipActive]}
                  onPress={() => setBucketKey(b.key)}
                >
                  <Text style={[s.bucketLabel, bucketKey === b.key && { color: '#fff' }]}>{b.label}</Text>
                </Pressable>
              ))}
            </View>
          </View>
          {kind !== 'articles' && (
            <View style={{ flex: 1 }}>
              <Text style={s.label}>Count</Text>
              <TextInput
                value={count}
                onChangeText={setCount}
                style={s.input}
                keyboardType="number-pad"
              />
            </View>
          )}
          <View style={{ flex: 1 }}>
            <Text style={s.label}>Publish mode</Text>
            <View style={s.bucketWrap}>
              {(['auto', 'published', 'draft'] as const).map((m) => (
                <Pressable
                  key={m}
                  onPress={() => setPublishMode(m)}
                  style={[s.bucketChip, publishMode === m && s.bucketChipActive]}
                >
                  <Text style={[s.bucketLabel, publishMode === m && { color: '#fff' }]}>{m}</Text>
                </Pressable>
              ))}
            </View>
          </View>
        </View>
      )}

      <View style={s.runRow}>
        <ToolbarButton
          label={running
            ? 'Generating…'
            : kind === 'articles'
              ? 'Generate article'
              : `Generate ${count} ${kind === 'books' ? 'books' : 'products'}`}
          icon="sparkles-outline"
          variant="primary"
          disabled={running}
          onPress={run}
        />
        {lastResult && (
          <Text style={[s.runResult, lastResult.startsWith('✗') && s.runResultBad]}>
            {lastResult}
          </Text>
        )}
      </View>
    </View>
  );
}

// ─── Content library card (unified: all items + full CRUD) ───────────────────

function ContentLibraryCard({ kind, onError }: {
  kind: Kind;
  onError: (msg: string | null) => void;
}) {
  const [items, setItems] = useState<LibraryContentItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<StatusFilter>('all');
  const [editItem, setEditItem] = useState<LibraryContentItem | null>(null);
  const [addOpen, setAddOpen] = useState(false);
  const [confirmDel, setConfirmDel] = useState<LibraryContentItem | null>(null);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    setLoading(true);
    const unsub = subscribeAllLibraryItems(kind, (rows) => {
      setItems(rows);
      setLoading(false);
    });
    return () => unsub();
  }, [kind]);

  const filtered = useMemo(() => {
    let rows = items;
    if (statusFilter !== 'all') {
      rows = rows.filter((r) => r.status === statusFilter);
    }
    const q = search.trim().toLowerCase();
    if (q) {
      rows = rows.filter((r) =>
        r.title.toLowerCase().includes(q) ||
        r.topic.toLowerCase().includes(q),
      );
    }
    return rows;
  }, [items, statusFilter, search]);

  const counts: Record<StatusFilter, number> = useMemo(() => ({
    all:       items.length,
    published: items.filter((r) => r.status === 'published').length,
    draft:     items.filter((r) => r.status === 'draft').length,
    archived:  items.filter((r) => r.status === 'archived').length,
  }), [items]);

  async function handleSave(form: Record<string, any>, isNew: boolean, id?: string) {
    setSaving(true);
    onError(null);
    const schema = SCHEMAS[kind];
    const cleaned: Record<string, any> = {};
    schema.forEach((f) => {
      const v = form[f.key];
      if (f.numeric) {
        const n = parseFloat(String(v));
        cleaned[f.key] = Number.isFinite(n) ? n : 0;
      } else {
        cleaned[f.key] = typeof v === 'string' ? v : String(v ?? '');
      }
    });
    try {
      if (isNew) {
        await createContent(kind, { ...cleaned, source: 'manual', status: 'draft' });
      } else if (id) {
        await updateContent(kind, id, cleaned);
      }
      setEditItem(null);
      setAddOpen(false);
    } catch (e: any) {
      onError(e?.message ?? String(e));
    } finally {
      setSaving(false);
    }
  }

  async function handleToggleStatus(item: LibraryContentItem) {
    const next = item.status === 'published' ? 'draft' : 'published';
    try {
      await updateContent(kind, item.id, { status: next });
    } catch (e: any) {
      onError(e?.message ?? String(e));
    }
  }

  async function handleArchive(item: LibraryContentItem) {
    try {
      // Use the Cloud Function for AI items (it logs); plain write for manual.
      if (item.source === 'ai') {
        await archiveLibraryItem(kind, item.id);
      } else {
        await updateContent(kind, item.id, { status: 'archived' });
      }
    } catch (e: any) {
      onError(e?.message ?? String(e));
    }
  }

  async function handleRestore(item: LibraryContentItem) {
    try {
      await updateContent(kind, item.id, { status: 'draft' });
    } catch (e: any) {
      onError(e?.message ?? String(e));
    }
  }

  async function handleDelete(item: LibraryContentItem) {
    try {
      await deleteContent(kind, item.id);
      setConfirmDel(null);
    } catch (e: any) {
      onError(e?.message ?? String(e));
    }
  }

  const statusChips: { key: StatusFilter; label: string; count: number }[] = [
    { key: 'all',       label: 'All',      count: counts.all },
    { key: 'published', label: 'Live',     count: counts.published },
    { key: 'draft',     label: 'Draft',    count: counts.draft },
    { key: 'archived',  label: 'Archived', count: counts.archived },
  ];

  return (
    <View style={s.card}>
      {/* Card header */}
      <View style={s.cardHeader}>
        <View style={{ flex: 1 }}>
          <Text style={s.cardTitle}>📋 Content library</Text>
          <Text style={s.cardSub}>
            All {KIND_META[kind].label.toLowerCase()} — AI-generated & manual. Tap any row to view or edit.
          </Text>
        </View>
        <ToolbarButton
          label={`Add ${kind === 'articles' ? 'article' : kind === 'books' ? 'book' : 'product'}`}
          icon="add-circle-outline"
          variant="primary"
          onPress={() => setAddOpen(true)}
        />
      </View>

      {/* Search + status filter */}
      <View style={{ marginBottom: Spacing.md, gap: 8 }}>
        <Toolbar
          search={{
            value: search,
            onChange: setSearch,
            placeholder: `Search ${KIND_META[kind].label.toLowerCase()}…`,
          }}
        />
        <View style={s.freqChips}>
          {statusChips.map((chip) => (
            <Pressable
              key={chip.key}
              onPress={() => setStatusFilter(chip.key)}
              style={[s.freqChip, statusFilter === chip.key && s.freqChipActive]}
            >
              <Text style={[s.freqChipText, statusFilter === chip.key && s.freqChipTextActive]}>
                {chip.label} {chip.count > 0 ? `(${chip.count})` : ''}
              </Text>
            </Pressable>
          ))}
        </View>
      </View>

      {/* Items list */}
      {loading ? (
        <View style={s.emptyWrap}>
          <ActivityIndicator color={Colors.primary} />
          <Text style={s.emptyBody}>Loading…</Text>
        </View>
      ) : filtered.length === 0 ? (
        <View style={s.emptyWrap}>
          <Text style={s.emptyEmoji}>{KIND_META[kind].emoji}</Text>
          <Text style={s.emptyTitle}>
            {search || statusFilter !== 'all' ? 'Nothing matches' : 'No items yet'}
          </Text>
          <Text style={s.emptyBody}>
            {search || statusFilter !== 'all'
              ? 'Try clearing the filter.'
              : `Use "Generate now" above or "Add ${kind === 'articles' ? 'article' : kind === 'books' ? 'book' : 'product'}" to get started.`}
          </Text>
        </View>
      ) : (
        <View style={{ gap: 6 }}>
          {filtered.map((item) => (
            <ContentRow
              key={item.id}
              item={item}
              onEdit={() => setEditItem(item)}
              onToggleStatus={() => handleToggleStatus(item)}
              onArchive={() => handleArchive(item)}
              onRestore={() => handleRestore(item)}
              onDelete={() => setConfirmDel(item)}
            />
          ))}
        </View>
      )}

      {/* Edit modal */}
      <ContentFormModal
        visible={!!editItem}
        kind={kind}
        item={editItem}
        saving={saving}
        onClose={() => setEditItem(null)}
        onSave={(form) => handleSave(form, false, editItem?.id)}
        onToggleStatus={editItem ? () => handleToggleStatus(editItem) : undefined}
        onArchive={editItem && editItem.status !== 'archived' ? () => { handleArchive(editItem); setEditItem(null); } : undefined}
        onRestore={editItem && editItem.status === 'archived' ? () => { handleRestore(editItem); setEditItem(null); } : undefined}
        onDelete={editItem ? () => { setConfirmDel(editItem); setEditItem(null); } : undefined}
      />

      {/* Add modal */}
      <ContentFormModal
        visible={addOpen}
        kind={kind}
        item={null}
        saving={saving}
        onClose={() => setAddOpen(false)}
        onSave={(form) => handleSave(form, true)}
      />

      {/* Delete confirm */}
      <ConfirmDialog
        visible={!!confirmDel}
        title="Delete permanently?"
        body={confirmDel ? `"${confirmDel.title}" will be removed from Firestore and the Library immediately.` : ''}
        destructive
        confirmLabel="Delete"
        onCancel={() => setConfirmDel(null)}
        onConfirm={async () => { if (confirmDel) await handleDelete(confirmDel); }}
      />
    </View>
  );
}

// ─── Content row ─────────────────────────────────────────────────────────────

function ContentRow({ item, onEdit, onToggleStatus, onArchive, onRestore, onDelete }: {
  item: LibraryContentItem;
  onEdit: () => void;
  onToggleStatus: () => void;
  onArchive: () => void;
  onRestore: () => void;
  onDelete: () => void;
}) {
  const ts = item.createdAt?.toDate?.()?.toLocaleDateString?.() ?? '';
  const ageLabel = item.ageMin < 0
    ? 'pregnancy'
    : item.ageMax >= 999
      ? 'all ages'
      : `${item.ageMin}–${item.ageMax}m`;

  return (
    <Pressable style={s.row} onPress={onEdit}>
      {/* Thumbnail */}
      {item.imageUrl ? (
        <Image source={{ uri: item.imageUrl }} style={s.rowThumb} resizeMode="cover" />
      ) : (
        <View style={[s.rowThumb, s.rowThumbEmpty]}>
          <Text style={{ fontSize: 22 }}>{KIND_META[item.kind].emoji}</Text>
        </View>
      )}

      {/* Info */}
      <View style={{ flex: 1, minWidth: 0 }}>
        <Text style={s.rowTitle} numberOfLines={1}>{item.title}</Text>
        <Text style={s.rowSub} numberOfLines={1}>
          {[item.topic, ageLabel, ts].filter(Boolean).join(' · ')}
        </Text>
        <View style={s.rowBadges}>
          <StatusBadge
            label={item.status === 'published' ? 'Live' : item.status === 'archived' ? 'Archived' : 'Draft'}
            color={item.status === 'published' ? Colors.success : item.status === 'archived' ? Colors.textMuted : Colors.warning}
          />
          <StatusBadge
            label={item.source === 'ai' ? '✨ AI' : '✍ Manual'}
            color={item.source === 'ai' ? Colors.primary : Colors.textLight}
          />
          {item.flags.length > 0 && (
            <StatusBadge label={`⚠ ${item.flags.length}`} color={Colors.warning} />
          )}
        </View>
      </View>

      {/* Quick actions */}
      <View style={s.rowActions}>
        {item.url ? (
          <Pressable
            hitSlop={8}
            onPress={(e) => { e.stopPropagation?.(); Linking.openURL(item.url!).catch(() => {}); }}
          >
            <Ionicons name="open-outline" size={18} color={Colors.textLight} />
          </Pressable>
        ) : null}
        <Pressable hitSlop={8} onPress={(e) => { e.stopPropagation?.(); onToggleStatus(); }}>
          <Ionicons
            name={item.status === 'published' ? 'eye-off-outline' : 'eye-outline'}
            size={18}
            color={Colors.textLight}
          />
        </Pressable>
        {item.status !== 'archived' ? (
          <Pressable hitSlop={8} onPress={(e) => { e.stopPropagation?.(); onArchive(); }}>
            <Ionicons name="archive-outline" size={18} color={Colors.textLight} />
          </Pressable>
        ) : (
          <Pressable hitSlop={8} onPress={(e) => { e.stopPropagation?.(); onRestore(); }}>
            <Ionicons name="refresh-outline" size={18} color={Colors.primary} />
          </Pressable>
        )}
        <Pressable hitSlop={8} onPress={(e) => { e.stopPropagation?.(); onDelete(); }}>
          <Ionicons name="trash-outline" size={18} color={Colors.error} />
        </Pressable>
      </View>
    </Pressable>
  );
}

// ─── Content form modal (view / edit / add) ──────────────────────────────────

function ContentFormModal({ visible, kind, item, saving, onClose, onSave, onToggleStatus, onArchive, onRestore, onDelete }: {
  visible: boolean;
  kind: Kind;
  item: LibraryContentItem | null;
  saving: boolean;
  onClose: () => void;
  onSave: (form: Record<string, any>) => Promise<void>;
  onToggleStatus?: () => void;
  onArchive?: () => void;
  onRestore?: () => void;
  onDelete?: () => void;
}) {
  const isEdit = !!(item?.id);
  const schema = SCHEMAS[kind];
  const [form, setForm] = useState<Record<string, any>>({});

  useEffect(() => {
    if (visible) {
      if (item) {
        // populate form from raw doc
        const populated: Record<string, any> = {};
        schema.forEach((f) => {
          populated[f.key] = item.raw[f.key] ?? '';
        });
        setForm(populated);
      } else {
        setForm(blankItem(kind));
      }
    }
  }, [visible, item, kind]);

  const primaryKey = kind === 'products' ? 'name' : 'title';
  const isValid = !!(form[primaryKey]?.toString().trim());

  async function submit() {
    if (!isValid) return;
    await onSave(form);
  }

  return (
    <Modal visible={visible} animationType="fade" transparent onRequestClose={onClose}>
      <View style={s.modalBackdrop}>
        <View style={s.modalCard}>
          {/* Header */}
          <View style={s.modalHeader}>
            <Text style={s.modalTitle}>
              {isEdit
                ? `${KIND_META[kind].emoji} Edit ${kind.replace(/s$/, '')}`
                : `${KIND_META[kind].emoji} Add ${kind.replace(/s$/, '')}`}
            </Text>
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: Spacing.sm }}>
              {item?.source === 'ai' && (
                <View style={s.aiBadge}>
                  <Text style={s.aiBadgeText}>✨ AI generated</Text>
                </View>
              )}
              <Pressable onPress={onClose} style={s.modalClose} hitSlop={6}>
                <Ionicons name="close" size={20} color={Colors.textDark} />
              </Pressable>
            </View>
          </View>

          {/* Compliance flags */}
          {(item?.flags?.length ?? 0) > 0 && (
            <View style={s.flagBanner}>
              <Ionicons name="warning-outline" size={16} color={Colors.warning} />
              <Text style={s.flagText}>
                Compliance flags: {item!.flags.join(', ')}
              </Text>
            </View>
          )}

          {/* Form fields */}
          <ScrollView
            contentContainerStyle={s.modalBody}
            keyboardShouldPersistTaps="handled"
            showsVerticalScrollIndicator
          >
            {schema.map((field) => (
              <View key={field.key} style={{ marginBottom: Spacing.md }}>
                <Text style={s.fieldLabel}>{field.label}</Text>
                {field.hint ? <Text style={s.fieldHint}>{field.hint}</Text> : null}
                <TextInput
                  style={[
                    s.fieldInput,
                    field.multiline && { minHeight: field.key === 'body' ? 200 : 80, textAlignVertical: 'top' },
                  ]}
                  value={String(form[field.key] ?? '')}
                  onChangeText={(v) => setForm((f) => ({ ...f, [field.key]: v }))}
                  multiline={field.multiline}
                  keyboardType={field.numeric ? 'decimal-pad' : 'default'}
                  autoCapitalize={
                    field.key === 'url' || field.key === 'imageUrl' || field.key === 'sampleUrl'
                      ? 'none' : 'sentences'
                  }
                  placeholderTextColor={Colors.textMuted}
                  placeholder={field.label.replace(' *', '')}
                  scrollEnabled={false}
                />
              </View>
            ))}
          </ScrollView>

          {/* Footer actions */}
          <View style={s.modalFooter}>
            {onDelete ? (
              <ToolbarButton label="Delete" icon="trash-outline" variant="danger" onPress={onDelete} />
            ) : null}
            {isEdit && onArchive ? (
              <ToolbarButton label="Archive" icon="archive-outline" variant="secondary" onPress={onArchive} />
            ) : null}
            {isEdit && onRestore ? (
              <ToolbarButton label="Restore" icon="refresh-outline" variant="secondary" onPress={onRestore} />
            ) : null}
            {isEdit && onToggleStatus && item ? (
              <ToolbarButton
                label={item.status === 'published' ? 'Unpublish' : 'Publish'}
                icon={item.status === 'published' ? 'eye-off-outline' : 'rocket-outline'}
                variant="secondary"
                onPress={onToggleStatus}
              />
            ) : null}
            <View style={{ flex: 1 }} />
            <ToolbarButton label="Cancel" variant="ghost" onPress={onClose} disabled={saving} />
            <ToolbarButton
              label={saving ? 'Saving…' : isEdit ? 'Save changes' : 'Add as draft'}
              variant="primary"
              icon="save-outline"
              onPress={submit}
              disabled={!isValid || saving}
            />
          </View>
        </View>
      </View>
    </Modal>
  );
}

// ─── Cron run history ────────────────────────────────────────────────────────

function RunsCard() {
  const [rows, setRows] = useState<{ id: string; ts: string; summary: string }[]>([]);
  const [loading, setLoading] = useState(false);

  async function load() {
    setLoading(true);
    try {
      const r = await listRecentRuns(10);
      setRows(r.map((x) => ({
        id: x.id,
        ts: x.ts?.toDate?.()?.toLocaleString?.() ?? '',
        summary: summarise(x.kindSummary),
      })));
    } finally {
      setLoading(false);
    }
  }
  useEffect(() => { void load(); }, []);

  return (
    <View style={s.card}>
      <View style={s.cardHeader}>
        <View style={{ flex: 1 }}>
          <Text style={s.cardTitle}>🕒 Cron history</Text>
          <Text style={s.cardSub}>The last 10 daily-cron runs. Useful when something didn't generate.</Text>
        </View>
        <ToolbarButton label="Refresh" icon="refresh" variant="ghost" onPress={load} disabled={loading} />
      </View>
      {rows.length === 0 ? (
        <Text style={s.empty}>{loading ? 'Loading…' : 'No runs yet — wait for tomorrow 06:30 IST.'}</Text>
      ) : (
        rows.map((r) => (
          <View key={r.id} style={s.runRowItem}>
            <Text style={s.runRowTs}>{r.ts}</Text>
            <Text style={s.runRowSummary}>{r.summary}</Text>
          </View>
        ))
      )}
    </View>
  );
}

function summarise(d: any): string {
  if (d?.kind === 'expire') {
    const b = d?.summary ?? {};
    return `Expired: articles=${b.articles ?? 0} · books=${b.books ?? 0} · products=${b.products ?? 0}`;
  }
  const parts: string[] = [];
  for (const k of ['articles', 'books', 'products'] as const) {
    const v = d?.[k];
    if (!v || v === 'skipped') { parts.push(`${k}: —`); continue; }
    parts.push(`${k}: ${v.ok}/${v.attempted}${v.errors?.length ? ` (${v.errors.length} err)` : ''}`);
  }
  return parts.join(' · ');
}

// ─── NumberField ─────────────────────────────────────────────────────────────

function NumberField({ label, hint, value, min, max, onChange }: {
  label: string;
  hint?: string;
  value: number;
  min: number;
  max: number;
  onChange: (n: number) => void;
}) {
  const [draft, setDraft] = useState(String(value));
  useEffect(() => { setDraft(String(value)); }, [value]);
  return (
    <View style={s.numField}>
      <Text style={s.label}>{label}</Text>
      {hint && <Text style={s.hint}>{hint}</Text>}
      <View style={s.numRow}>
        <Pressable style={s.numStep} onPress={() => onChange(Math.max(min, value - 1))}>
          <Ionicons name="remove" size={16} color={Colors.textDark} />
        </Pressable>
        <TextInput
          value={draft}
          onChangeText={setDraft}
          onBlur={() => {
            const n = parseInt(draft, 10);
            if (Number.isFinite(n)) onChange(Math.max(min, Math.min(max, n)));
            else setDraft(String(value));
          }}
          style={s.numInput}
          keyboardType="number-pad"
        />
        <Pressable style={s.numStep} onPress={() => onChange(Math.min(max, value + 1))}>
          <Ionicons name="add" size={16} color={Colors.textDark} />
        </Pressable>
      </View>
    </View>
  );
}

// ─── Styles ──────────────────────────────────────────────────────────────────

const s = StyleSheet.create({
  // Cards
  card: {
    backgroundColor: Colors.cardBg,
    borderRadius: Radius.xl,
    padding: Spacing.lg,
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    ...Shadow.sm,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.md, marginBottom: Spacing.md },
  cardTitle: { fontSize: FontSize.md, fontWeight: '800', color: Colors.textDark },
  cardSub: { fontSize: FontSize.xs, color: Colors.textLight, marginTop: 2 },

  // Toggle
  toggleWrap: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  toggleLabel: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textLight },

  // Cadence banner
  cadenceBanner: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    backgroundColor: Colors.primaryAlpha05,
    paddingHorizontal: Spacing.md,
    paddingVertical: 8,
    borderRadius: Radius.md,
    marginBottom: Spacing.md,
  },
  cadenceText: { fontSize: FontSize.xs, color: Colors.primary, fontWeight: '600', flex: 1 },

  // Form layout
  fieldRow: { flexDirection: 'row', gap: Spacing.md, marginBottom: Spacing.sm },
  fieldGrid: { flexDirection: 'row', gap: Spacing.md, flexWrap: 'wrap' },
  gridTwo: { flexDirection: 'row', gap: Spacing.md, flexWrap: 'wrap', marginVertical: Spacing.md },

  // Labels
  label: {
    fontSize: 11, fontWeight: '700',
    color: Colors.textLight,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  hint: { fontSize: FontSize.xs, color: Colors.textMuted, marginBottom: 6 },

  // Inputs
  input: {
    backgroundColor: Colors.bgLight,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: 10,
    fontSize: FontSize.sm,
    color: Colors.textDark,
    borderWidth: 1,
    borderColor: Colors.border,
  },

  // Chips
  freqChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  freqChip: {
    paddingHorizontal: Spacing.md, paddingVertical: 6,
    backgroundColor: Colors.bgLight,
    borderRadius: 999,
    borderWidth: 1, borderColor: Colors.borderSoft,
  },
  freqChipActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  freqChipText: { fontSize: FontSize.xs, color: Colors.textDark, fontWeight: '600' },
  freqChipTextActive: { color: '#fff' },

  // Number field
  numField: { minWidth: 160, flex: 1 },
  numRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  numStep: {
    width: 32, height: 32,
    borderRadius: Radius.md,
    backgroundColor: Colors.bgLight,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: Colors.borderSoft,
  },
  numInput: {
    flex: 1, textAlign: 'center',
    backgroundColor: Colors.cardBg,
    borderRadius: Radius.md,
    paddingVertical: 8,
    borderWidth: 1, borderColor: Colors.border,
    fontSize: FontSize.sm, fontWeight: '700', color: Colors.textDark,
  },
  boolField: { minWidth: 200, flex: 1 },

  // Bucket chips
  bucketWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 },
  bucketChip: {
    paddingHorizontal: Spacing.md, paddingVertical: 6,
    backgroundColor: Colors.bgLight,
    borderRadius: 999,
    borderWidth: 1, borderColor: Colors.borderSoft,
  },
  bucketChipActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  bucketLabel: { fontSize: FontSize.xs, fontWeight: '600', color: Colors.textDark },
  bucketRange: { fontSize: 10, color: Colors.textMuted, marginTop: 1 },

  // Row
  rowRight: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 6 },
  runRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, marginTop: Spacing.md, flexWrap: 'wrap' },
  runResult: { fontSize: FontSize.xs, color: Colors.success, fontWeight: '600', flex: 1 },
  runResultBad: { color: Colors.error },

  // Content rows
  row: {
    flexDirection: 'row', gap: Spacing.md,
    backgroundColor: Colors.bgLight,
    borderRadius: Radius.md,
    padding: Spacing.md,
    alignItems: 'center',
  },
  rowThumb: {
    width: 52, height: 52,
    borderRadius: Radius.md,
    overflow: 'hidden',
    borderWidth: 1, borderColor: Colors.borderSoft,
    flexShrink: 0,
  },
  rowThumbEmpty: {
    backgroundColor: Colors.bgLight,
    alignItems: 'center', justifyContent: 'center',
  },
  rowTitle: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.textDark },
  rowSub: { fontSize: FontSize.xs, color: Colors.textLight, marginTop: 2 },
  rowBadges: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginTop: 4 },
  rowActions: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, flexShrink: 0 },

  // Empty
  emptyWrap: { alignItems: 'center', paddingVertical: Spacing.xl, gap: 6 },
  emptyEmoji: { fontSize: 32 },
  emptyTitle: { fontSize: FontSize.md, fontWeight: '700', color: Colors.textDark },
  emptyBody: { fontSize: FontSize.xs, color: Colors.textMuted, textAlign: 'center', maxWidth: 320 },
  empty: { fontSize: FontSize.xs, color: Colors.textMuted, paddingVertical: Spacing.md },

  // Cron history rows
  runRowItem: { paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: Colors.borderSoft },
  runRowTs: { fontSize: 10, color: Colors.textMuted, fontVariant: ['tabular-nums'] },
  runRowSummary: { fontSize: FontSize.xs, color: Colors.textDark, marginTop: 2 },

  // Header
  headerCtrls: { flexDirection: 'row', gap: Spacing.md, alignItems: 'center' },
  pausedRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  pausedLabel: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.textLight },

  // Info banner
  banner: {
    backgroundColor: Colors.primaryAlpha05,
    borderRadius: Radius.xl,
    padding: Spacing.lg,
    marginBottom: Spacing.lg,
    borderWidth: 1, borderColor: Colors.primaryAlpha12,
  },
  bannerPaused: { backgroundColor: '#fff7ed', borderColor: '#fdba74' },
  bannerHead: { marginBottom: Spacing.md },
  bannerTitle: { fontSize: FontSize.md, fontWeight: '800', color: Colors.textDark },
  bannerSub: { fontSize: FontSize.xs, color: Colors.textLight, marginTop: 4 },
  bannerSteps: { gap: 6 },
  bannerStep: { fontSize: FontSize.xs, color: Colors.textDark, lineHeight: 18 },

  // Modal
  modalBackdrop: {
    flex: 1, backgroundColor: 'rgba(28,16,51,0.55)',
    alignItems: 'center', justifyContent: 'center',
    padding: Spacing.lg,
  },
  modalCard: {
    width: '100%', maxWidth: 680, maxHeight: '92%',
    backgroundColor: Colors.cardBg,
    borderRadius: Radius.xl,
    overflow: 'hidden',
    ...Shadow.lg,
  },
  modalHeader: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: Spacing.xl, paddingVertical: Spacing.lg,
    borderBottomWidth: 1, borderBottomColor: Colors.borderSoft,
  },
  modalTitle: { fontSize: FontSize.lg, fontWeight: '800', color: Colors.textDark },
  modalClose: {
    width: 32, height: 32, borderRadius: 16,
    backgroundColor: Colors.bgLight,
    alignItems: 'center', justifyContent: 'center',
  },
  modalBody: { padding: Spacing.xl },
  modalFooter: {
    flexDirection: 'row', alignItems: 'center', gap: Spacing.sm,
    paddingHorizontal: Spacing.xl, paddingVertical: Spacing.md,
    borderTopWidth: 1, borderTopColor: Colors.borderSoft,
    flexWrap: 'wrap',
  },

  // Form fields
  fieldLabel: {
    fontSize: 11, fontWeight: '700', color: Colors.textLight,
    letterSpacing: 0.6, textTransform: 'uppercase', marginBottom: 4,
  },
  fieldHint: { fontSize: FontSize.xs, color: Colors.textMuted, marginBottom: 4 },
  fieldInput: {
    backgroundColor: Colors.bgLight,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md, paddingVertical: 10,
    fontSize: FontSize.sm, color: Colors.textDark,
    borderWidth: 1, borderColor: Colors.border,
  },

  // AI badge
  aiBadge: {
    backgroundColor: Colors.primaryAlpha05,
    borderRadius: 999,
    paddingHorizontal: Spacing.sm, paddingVertical: 3,
    borderWidth: 1, borderColor: Colors.primaryAlpha12,
  },
  aiBadgeText: { fontSize: 10, fontWeight: '700', color: Colors.primary },

  // Compliance flag banner
  flagBanner: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    backgroundColor: '#fff7ed',
    paddingHorizontal: Spacing.xl, paddingVertical: 8,
    borderBottomWidth: 1, borderBottomColor: '#fdba74',
  },
  flagText: { fontSize: FontSize.xs, color: Colors.warning, fontWeight: '600', flex: 1 },
});
